---
version: 2
jobs:
  node-latest: &test
    docker:
      - image: node:latest
    working_directory: ~/cli
    environment:
      DEPS: "nyc@11 @anycli/nyc-config@0 mocha-junit-reporter@1 @commitlint/cli@6 @commitlint/config-conventional@6"
      NYC: "yarn exec nyc -- --nycrc-path node_modules/@anycli/nyc-config/.nycrc"
      MOCHA_FILE: "reports/mocha.xml"
    steps:
      - checkout
      - attach_workspace: {at: node_modules}
      - run: .circleci/setup_git
      - run: |
          mkdir -p reports
          $NYC yarn test --reporter mocha-junit-reporter
          $NYC report --reporter text-lcov > coverage.lcov
          curl -s https://codecov.io/bash | bash
      - run: ./bin/run -v
      - run: ./bin/run --help
      - run: yarn exec commitlint -- -x @commitlint/config-conventional --from origin/master
      - store_test_results: &store_test_results
          path: ~/cli/reports
  node-8:
    <<: *test
    docker:
      - image: node:8
  yarn:
    <<: *test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v0-{{checksum ".circleci/config.yml"}}-{{ checksum "yarn.lock"}}
            - v0-{{checksum ".circleci/config.yml"}}
            - v0
      - run: .circleci/greenkeeper
      - run: yarn global add greenkeeper-lockfile@1
      - run: yarn add -D $DEPS
      - persist_to_workspace: {root: node_modules,  paths: ["*"]}
  cache:
    <<: *test
    steps:
      - checkout
      - restore_cache: { keys: [v001-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}] }
      - attach_workspace: {at: node_modules}
      - run: yarn global add greenkeeper-lockfile@1@anycli/semantic-release@1 semantic-release@12
      - run: yarn add -D $DEPS
      - save_cache:
          key: v001-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
          paths:
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn
  release:
    <<: *test
    steps:
      - add_ssh_keys
      - checkout
      - attach_workspace: {at: node_modules}
      - run: |
          export PATH=/usr/local/share/.config/yarn/global/node_modules/.bin:$PATH
          .circleci/setup_git
          yarn global add @anycli/semantic-release@1 semantic-release@12
          semantic-release -e @anycli/semantic-release

workflows:
  version: 2
  "@anycli/example-multi-ts":
    jobs:
      - yarn
      - node-latest: {requires: [yarn] }
      - node-8: {requires: [yarn] }
      - release:
          context: org-global
          filters:
            branches: {only: master}
          requires:
            - node-latest
            - node-8
      - cache: { requires: [release] }
