---
version: 2
jobs:
  node-latest: &test
    docker:
      - image: node:latest
    working_directory: ~/cli
    environment:
      NYC: yarn exec nyc -- --nycrc-path node_modules/@anycli/nyc-config/.nycrc
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v0-{{checksum ".circleci/config.yml"}}-{{ checksum "yarn.lock"}}
            - v0-{{checksum ".circleci/config.yml"}}
            - v0
      - run: .circleci/setup_git
      - run: .circleci/greenkeeper
      - run: yarn add -D nyc@11 @anycli/nyc-config@0 mocha-junit-reporter@1 @commitlint/cli@6 @commitlint/config-conventional@6
      - run:
          name: yarn test
          when: always
          environment: {MOCHA_FILE: reports/mocha.xml}
          command: |
            mkdir -p reports
            $NYC yarn test --reporter mocha-junit-reporter
      - run:
          name: submit code coverage
          command: |
            $NYC report --reporter text-lcov > coverage.lcov
            curl -s https://codecov.io/bash | bash
      - run:
          when: always
          command: ./bin/run -v
      - run:
          when: always
          command: ./bin/run --help
      - run:
          name: check if commits match conventional-changelog spec
          when: always
          command: yarn exec commitlint -- -x @commitlint/config-conventional --from origin/master
      - store_test_results: &store_test_results
          path: ~/cli/reports
  node-8:
    <<: *test
    docker:
      - image: node:8
  cache:
    <<: *test
    steps:
      - checkout
      - yarn global add greenkeeper-lockfile@1
      - yarn add -D nyc@11 @anycli/nyc-config@0 mocha-junit-reporter@1 @commitlint/cli@6 @commitlint/config-conventional@6
      - save_cache:
          key: v0-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
          paths:
            - ~/cli/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn
  release:
    <<: *test
    steps:
      - add_ssh_keys
      - checkout
      - restore_cache: *restore_cache
      - run: .circleci/setup_git
      - run: .circleci/release

workflows:
  version: 2
  "@anycli/example-multi-ts":
    jobs:
      - node-latest
      - node-8
      - cache:
          filters:
            branches: {only: master}
      - release:
          context: org-global
          filters:
            branches: {only: master}
          requires:
            - node-latest
            - node-8
