---
version: 2
jobs:
  node-latest: &test
    docker:
      - image: node:latest
    working_directory: ~/cli
    environment:
      NYC: "yarn exec nyc -- --nycrc-path node_modules/@oclif/nyc-config/.nycrc"
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v1-yarn-{{checksum ".circleci/config.yml"}}-{{ checksum "yarn.lock"}}
            - v1-yarn-{{checksum ".circleci/config.yml"}}
      - run:
          name: Install dependencies
          command: |
            .circleci/greenkeeper
            yarn add -D nyc@11 @oclif/nyc-config@1
      - run: ./bin/run --version
      - run: ./bin/run --help
      - run:
          name: Testing
          command: |
            $NYC yarn test
            $NYC report --reporter text-lcov > coverage.lcov
            curl -s https://codecov.io/bash | bash
  node-8:
    <<: *test
    docker:
      - image: node:8
  release:
    <<: *test
    steps:
      - add_ssh_keys
      - checkout
      - restore_cache: *restore_cache
      - run:
          name: Install dependencies
          command: |
            yarn global add @oclif/semantic-release@3 semantic-release@15
            yarn --frozen-lockfile
      - run:
          name: Cutting release
          command: |
            export PATH=/usr/local/share/.config/yarn/global/node_modules/.bin:$PATH
            semantic-release -e @oclif/semantic-release
      - run:
          name: Add dev packages to cache
          command: yarn add -D nyc@11 @oclif/nyc-config@1
      - save_cache:
          key: v1-yarn-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
          paths:
            - ~/cli/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn

workflows:
  version: 2
  "@oclif/example-multi-ts":
    jobs:
      - node-latest
      - node-8
      - release:
          context: org-global
          filters:
            branches: {only: master}
          requires:
            - node-latest
            - node-8
